import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Lato, Playfair_Display } from 'next/font/google';

const lato = Lato({ 
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-lato'
});

const playfair = Playfair_Display({ 
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-playfair' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${playfair.variable} antialiased`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
